services:
  redis-cart:
    image: redis:alpine
    ports: ["6379:6379"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  productcatalogservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/productcatalogservice:v0.10.7
    environment: [PORT=3550, DISABLE_PROFILER=1]
    ports: ["3550:3550"]

  currencyservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/currencyservice:v0.10.7
    environment: [PORT=7000, DISABLE_PROFILER=1]
    ports: ["7000:7000"]

  cartservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/cartservice:v0.10.7
    environment: [REDIS_ADDR=redis-cart:6379]
    ports: ["7070:7070"]
    depends_on:
      redis-cart: {condition: service_healthy}

  adservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/adservice:v0.10.7
    environment: [PORT=9555]
    ports: ["9555:9555"]

  shippingservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/shippingservice:v0.10.7
    environment: [PORT=50051, DISABLE_PROFILER=1]
    ports: ["50051:50051"]

  emailservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/emailservice:v0.10.7
    environment: [PORT=5000, DISABLE_PROFILER=1]
    ports: ["5000:8080"]

  paymentservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/paymentservice:v0.10.7
    environment: [PORT=50051, DISABLE_PROFILER=1]
    ports: ["50052:50051"]

  checkoutservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/checkoutservice:v0.10.7
    environment:
      - PORT=5050
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - PAYMENT_SERVICE_ADDR=paymentservice:50051
      - EMAIL_SERVICE_ADDR=emailservice:5000
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
    ports: ["5050:5050"]

  recommendationservice:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/recommendationservice:v0.10.7
    environment: [PORT=8080, DISABLE_PROFILER=1, PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550]
    ports: ["8081:8080"]

  frontend:
    image: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo/frontend:v0.10.7
    environment:
      - PORT=8080
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatalogservice:3550
      - CURRENCY_SERVICE_ADDR=currencyservice:7000
      - CART_SERVICE_ADDR=cartservice:7070
      - RECOMMENDATION_SERVICE_ADDR=recommendationservice:8080
      - SHIPPING_SERVICE_ADDR=shippingservice:50051
      - CHECKOUT_SERVICE_ADDR=checkoutservice:5050
      - AD_SERVICE_ADDR=adservice:9555
      - SHOPPING_ASSISTANT_SERVICE_ADDR=shoppingassistantservice:80
    ports: ["8080:8080"]
